pool: default
steps:
- bash: echo hello world
- bash: dotnet build Tailspin.SpaceGame.Web.sln
- bash: dotnet pack Tailspin.SpaceGame.Web.sln
- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: push
    feedPublish: '$(System.TeamProject)/Tailspin.SpaceGame.Web.Models'
    allowPackageConflicts: true
  condition: succeeded()